### ISSUE TITLE
Option to choose specific device "machine_id" only.

### ISSUE THREAD

**Issue by milindpatel63** [Arno500/plex-richpresence#1]
Currently all the client devices playing media from a specific plex server and user is being detected.
In my case, i share my main plex account with friends and family for various reasons.
So whatever they play is being detected too.

Would love for an option to whitelist only specific devices to being detected.

**Comment by Arno500** [comment]
Hello @milindpatel63 
Sorry for this delayed response, I've been pretty busy. I'll look in it as soon as I have time, but I prefer to resolve issues first (notably when Plex authent is down, do not pop 10 tabs in the browser, + do not open 2 tabs each time auth is needed).
Thank you!

**Comment by Arno500** [comment]
Hello again @milindpatel63 ,
You may try using the new 1.3.0 release, it includes that functionality :)
https://github.com/Arno500/plex-richpresence/releases/tag/1.3.0
Thanks!
