### ISSUE TITLE
[Suggestion] Change color of small icons

### ISSUE THREAD

**Issue by hotsno** [Arno500/plex-richpresence#10]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/71658949/170928847-79fb66d2-f4a9-43ee-9889-371d6a70c5fe.png">
Currently, the small pause/play icons are black, which looks pretty bad against the dark background that Discord uses (probably >95% of Discord users use the default dark theme). I'd suggest making these light gray or some other color that contrasts better, but maybe still works well for those 5 light mode users out there. Or maybe a yellowish-orange would work well?

**Comment by Arno500** [comment]
I've changed the "play" and "pause" icons, I still need to do the "camera" one but I can't find it anymore and I didn't upload it to the repo 😬
