### ISSUE TITLE
Building Project

### ISSUE THREAD

**Issue by Lucy-2077** [Arno500/plex-richpresence#12]
Hello ! I would like make a build of the project but after few hours, i'm stay blocked with that :
PS go build -tags windows -ldflags='-s -w -H=windowsgui'
# gitlab.com/Arno500/plex-richpresence
C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe:C:\Users\DefiD\AppData\Local\Temp\go-link-2419147679\000000.o: file format not recognized; treating as linker script
c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe:C:\Users\DefiD\AppData\Local\Temp\go-link-2419147679\000000.o:1: syntax error
collect2.exe: error: ld returned 1 exit status

Any idea for how unlock that ? 
Thank you c:

**Comment by Arno500** [comment]
Sorry for the delay, I'll take a look at that really soon!
I think the main issue boils down to the fact that you have MingW installed and that Go tries to use it. But I don't exactly see why it's blocking on that file
