### ISSUE TITLE
Crash when changing episodes

### ISSUE THREAD

**Issue by Diyagi** [Arno500/plex-richpresence#15]
Hello,
The app is crashing sometimes while change episodes, might not be a crash bc theres is nothing on the logs, but sometimes, i do have to open it again after i go to the next episode.

debug log:
```
2022/12/16 21:06:25 Refreshing servers
2022/12/16 21:06:30 Discord activity set
2022/12/16 21:06:40 Discord activity set
2022/12/16 21:06:50 Discord activity set
2022/12/16 21:07:00 A seeking or a media change was detected, adjusting
2022/12/16 21:07:00 Discord activity set
2022/12/16 21:07:10 Discord activity set
2022/12/16 21:07:20 Nothing is playing, closing connection to Discord.                                  //Crash?
2022/12/16 23:16:13 Detected language: en                                                               //Only noticed after some time
2022/12/16 23:16:14 Checking for updates...
2022/12/16 23:16:17 [AutoUpdater] Local Version 1.6.2 - Remote Version: 1.6.2
2022/12/16 23:16:17 Refreshing servers
2022/12/16 23:16:19 ****: Trying to connect to ****:443
2022/12/16 23:16:19 ****: ****:443 was successfully contacted
2022/12/16 23:16:19 Sucessfully connected to https://****:443 WebSocket
2022/12/16 23:16:32 A seeking or a media change was detected, adjusting
2022/12/16 23:16:32 Debug: Posting to URL https://api.imgur.com/3/image
2022/12/16 23:16:34 Discord activity set
2022/12/16 23:16:34 Discord activity set
2022/12/16 23:16:42 Discord activity set
2022/12/16 23:16:43 Discord activity set
2022/12/16 23:16:52 Discord activity set
2022/12/16 23:17:02 Discord activity set
2022/12/16 23:17:12 Discord activity set
```

**Comment by Arno500** [comment]
Hello, thanks for the report!

Which app are you using, on which operating system? My guess is that it's closing the connection after reading an episode, which it should absolutely not do. I'll try to look into it ASAP!

**Comment by Diyagi** [comment]
Im using Plex for Windows - Version 1.59.1.3398-dab42972
on Windows 10 Pro - 21H2 - 19044.2364

**Comment by Arno500** [comment]
Hello @Diyagi !

In the latest release, I improved the stability of the disconnect/reconnect a lot, can you check again?
Thank you.

**Comment by Diyagi** [comment]
Sure !
I will update it and test it later

**Comment by Diyagi** [comment]
Still having the issue, nothing new on the logs :c

**Comment by Arno500** [comment]
So if I understand correctly:
- You play something, everything works as expected, blahblahblah
- Then, when you switch of episode, the app just randomly crashes, without any output in the log

Am I correct?
Oh also, are you:
1. Owner of you Plex server (shouldn't crash, but maybe I can test other scenarios)
2. In a Plex Home (never tested that, many old reports of bugs in that situation)

**Comment by Diyagi** [comment]
Yes, correct, when im watching a TV Show or something like that and the episode ends, another one starts, sometimes the Plex Rich Presence app keeps running as normal, but sometimes it crashes.

Im not the owner of the server and im not in a Plex Home.
