### ISSUE TITLE
Windows Defender Detection

### ISSUE THREAD

**Issue by tramix32** [Arno500/plex-richpresence#18]
Latest version (1.8.0) is detected as Trojan:Win32/Bearfoos.B!ml by Windows Defender
![image](https://github.com/Arno500/plex-richpresence/assets/23013601/0a23ed0f-2d1c-456d-a678-c1f2b475d253)

**Comment by Arno500** [comment]
I sent the file to Microsoft for malware analysis, I'll keep you updated!

**Comment by Arno500** [comment]
Here is their response:
```
At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
```

**Comment by JoshTheBlack** [comment]
Hijacking this thread.  1.10.3 is being detected by Window Defender again.
![image](https://github.com/Arno500/plex-richpresence/assets/15058509/1e14a7d3-6746-419e-958b-172e3689cf10)
