### ISSUE TITLE
RPC doesn't always show

### ISSUE THREAD

**Issue by SleepDaemon** [Arno500/plex-richpresence#19]
Sometimes the it shows and most times it doesn't. I couldn't get the app to show the RPC consistently. I don't know if you have to open the plex-rpc app first then discord and plex itself or vice versa.

**Comment by Arno500** [comment]
Hi @SleepDaemon ,

Are you on an unstable network?
Around when did you start using the app for the first time?

I'm fearing this is because of the last update. Can you attach your logs? (be careful to hide your private IPs)
Otherwise, no, you don't need to do anything in any particular order there: just make sure that the app is opened with Discord (the order or timing doesn't matter) and play something on Plex (it should also catch up already playing content).

Thanks!

**Comment by SleepDaemon** [comment]
Where can I find the logs? Also no I am not on a unstable network, and I started using this app uh back since v1.16/17 maybe older. It has been while since I was using it.

**Comment by SleepDaemon** [comment]
> Hi @SleepDaemon ,
> 
> Are you on an unstable network? Around when did you start using the app for the first time?
> 
> I'm fearing this is because of the last update. Can you attach your logs? (be careful to hide your private IPs) Otherwise, no, you don't need to do anything in any particular order there: just make sure that the app is opened with Discord (the order or timing doesn't matter) and play something on Plex (it should also catch up already playing content).
> 
> Thanks!

Hey, where can I find log files? Also I am not on a unstable network, and I have been using this app for few years now. I can confirm been using it since at least v1.17 but I am also sure been using it before that as well.

**Comment by SleepDaemon** [comment]
Any response?

**Comment by Arno500** [comment]
Sorry, was fully busy recently. The logs are in your user profile, `AppData\Roaming\Arno & Co\Plex-Richpresence` if you are on Windows.
Alright, then it does point to an issue with the way the latest version is dealing with connections in the background. I would suspect that a connection gets closed, but does not recover.

**Comment by SleepDaemon** [comment]
Ok so, the debug file was like 3k lines long and it was mostly of older versions. So I deleted it, and then went ahead to open the app + plex + discord. To generate a new one with newest version. I also had 2 of the same devices listed in config so I cleared that and added my laptop again. And somehow, doing that made it show up. I will try to recreate it and hope to get a log of it.

Also anyway I can privately shared the log file?

**Comment by Arno500** [comment]
Yes, you can send it to me: <redacted>

**Comment by SleepDaemon** [comment]
i think i got it

**Comment by SleepDaemon** [comment]
hi, so it seems to be fix just from clearing the devices in the config file. I will still send the .txt of the log just in case but I couldn't reproduce the issue. If it happens again I will update this issue and send you another email with updated log.

**Comment by SleepDaemon** [comment]
Hi, the issue is back so I emailed you the updated log file.

**Comment by SleepDaemon** [comment]
hmmm, seems like i didnt get your email right
![image](https://github.com/Arno500/plex-richpresence/assets/88533953/a88938c2-627e-4a76-b8f8-b063a6ad4152)

**Comment by Arno500** [comment]
You mispelled it :)

**Comment by SleepDaemon** [comment]
> You mispelled it :)

ye see it now, ive send it. (hopefully got it right this time)

**Comment by SleepDaemon** [comment]
keep posted :)

**Comment by Arno500** [comment]
I am currently pretty busy with other stuff, but don't worry, this is on the pile!

**Comment by Arno500** [comment]
(cleaned my email from there, working on the fix ;) )

**Comment by Arno500** [comment]
I pushed a new version that should build and will update automatically on your computer on the next restart (you should see 1.9.1 as the version).
Please advise if you still see the issue!
Best,
Arno

**Comment by SleepDaemon** [comment]
how long does it take for new version to build?

**Comment by Arno500** [comment]
It's already live, you should see it when right-clicking on the icon in your task bar (after a restart of the app or two)

**Comment by SleepDaemon** [comment]
> It's already live, you should see it when right-clicking on the icon in your task bar (after a restart of the app or two)

Restarted it like 10 times still saying 1.9.0

**Comment by Arno500** [comment]
In that case, you can find it there: https://gitlab.com/Arno500/plex-richpresence/-/releases/1.9.1

**Comment by SleepDaemon** [comment]
> In that case, you can find it there: https://gitlab.com/Arno500/plex-richpresence/-/releases/1.9.1

Still not working 😭

Debug log
[debug_log.txt](https://github.com/Arno500/plex-richpresence/files/14348854/debug_log.txt)

**Comment by SleepDaemon** [comment]
seems to be connection gets closed and not get recovered.

**Comment by Arno500** [comment]
(I removed your logs for confidentiality purposes, but I downloaded it before)
I think the script is getting answers from the IPs, but it does not seem those are the good ones:
- 10.xx.xx.xx could be correct, this is a local IP, so it could be your server (if it is on another machine, supposedly)
- 172.xx.xx.xx is a range generally used by Docker: do you have Docker running on your computer? If yes, do you have some service listening on 32400 in there?

What is really weird is that apparently all IPs are responding "OK" to a dumb TCP test (`was successfully contacted`, Plex RP is simply opening a TCP connection and confirms it could open it, so something somewhere on your computer is definitely answering), but when connecting through WebSocket the other ends just kills the connection.
It could hint at a proxy answering to everything (though a proxy on 32400 would be weird) or some sort of network weirdness on your machine.
I'm trying to see if I can improve the connection test to properly ping the server and only include the ones that could really work

**Comment by SleepDaemon** [comment]
None of these servers are mine. They are run by some people I know. Like a
online community where if you meet the weekly streaming usage you won't be
kicked.

**Comment by SleepDaemon** [comment]
btw it did work before but once it stops working it just never works again.

**Comment by Arno500** [comment]
New release just dropped: https://gitlab.com/Arno500/plex-richpresence/-/releases/1.9.2
You may try this one and HOPEFULLY your problem goes away.....

**Comment by SleepDaemon** [comment]
> New release just dropped: https://gitlab.com/Arno500/plex-richpresence/-/releases/1.9.2 You may try this one and HOPEFULLY your problem goes away.....

1.9.2 works, but for some reason in the RPC it is not showing the show/movie poster image.

**Comment by Arno500** [comment]
Okay, it seems Imgur failed for some reason. I moved to litterbox for temporary storage in the latest version (https://gitlab.com/Arno500/plex-richpresence/-/releases/1.9.4)
The poster should now reappear!

**Comment by SleepDaemon** [comment]
Updated to latest version, and the app just closes itself after opening it. Like I open it and then few seconds later it closes it self. I have attached the debug log file. But I think this may be the issue:

`2024/05/13 10:37:41 Error uploading image to litterbox:  Post "https://litterbox.catbox.moe/resources/internals/api.php": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

[debug_log.txt](https://github.com/Arno500/plex-richpresence/files/15290934/debug_log.txt)

**Comment by SleepDaemon** [comment]
> Updated to latest version, and the app just closes itself after opening it. Like I open it and then few seconds later it closes it self. I have attached the debug log file. But I think this may be the issue:
> 
> `2024/05/13 10:37:41 Error uploading image to litterbox: Post "https://litterbox.catbox.moe/resources/internals/api.php": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`
> 
> [debug_log.txt](https://github.com/Arno500/plex-richpresence/files/15290934/debug_log.txt)

@Arno500

**Comment by Arno500** [comment]
Should be better since the last fixes with Litterbox, will close this issue

**Comment by SleepDaemon** [comment]
> Should be better since the last fixes with Litterbox, will close this issue

Just updated it today, and noticed it got fixed thanks
