### ISSUE TITLE
App crashes when opening Plex

### ISSUE THREAD

**Issue by rafaeldamasceno** [Arno500/plex-richpresence#2]
Sadly, I haven't been able to use the app at all.

When opening Plex, the app crashes.

Here are the logs:
```
2021/12/11 01:59:38 Detected language: pt
2021/12/11 01:59:38 Refreshing servers
2021/12/11 01:59:38 We never had an access token, generating it
2021/12/11 01:59:38 We never had a pin on Plex, creating one
2021/12/11 01:59:38 The client identifier has never been set. Generating one.
2021/12/11 01:59:39 Waiting for user authentication
2021/12/11 01:59:41 Bananaflix: Trying to connect to 192-168-1-91.b038c9a836c9486b861630a7697d6402.plex.direct:32400
2021/12/11 01:59:41 rho: Trying to connect to 192-168-0-144.880f9bb2f70245c2a40456395fc1a419.plex.direct:32400
2021/12/11 01:59:41 rho: 192-168-0-144.880f9bb2f70245c2a40456395fc1a419.plex.direct:32400 was successfully contacted
2021/12/11 01:59:42 Bananaflix: Trying to connect to 176-79-71-141.b038c9a836c9486b861630a7697d6402.plex.direct:11146
2021/12/11 01:59:42 Bananaflix: 176-79-71-141.b038c9a836c9486b861630a7697d6402.plex.direct:11146 was successfully contacted
2021/12/11 01:59:43 Sucessfully connected to found WebSocket links
2021/12/11 02:00:03 json: cannot unmarshal number into Go struct field MetadataV1.MediaContainer.Metadata.addedAt of type string
```

**Comment by Arno500** [comment]
Hello @rafaeldamasceno . Thanks for reporting this issue!
Can you explain a bit what media were you playing when it crashes? I mean, what type of media (picture, show, movie...) and does it have any special characteristic? Like a missing "Added At" field for example.
Also, please make sure the version of Plex you're using is the latest one.

**Comment by rafaeldamasceno** [comment]
Hey there,

Sorry for not including the version numbers. I'm using Plex for Windows Version 1.39.1.2763-300bb607 and Plex Media Server Version 1.25.1.5286, both reported to be the latest.

I only have movies and TV shows, and any of them cause the crash. As far as I can tell, all of my media can cause this.

I can't figure out where I can edit or check that the field exists in the metadata editor, but Plex does seem to be saving it, as you can see in the following screenshot:
![image](https://user-images.githubusercontent.com/6492427/145832507-87d82d2f-51a3-4d02-a700-9ef16e6b30b6.png)

Thank you.

**Comment by Arno500** [comment]
Hello @rafaeldamasceno,
Version 1.2.0 here (https://github.com/Arno500/plex-richpresence/releases/tag/1.2.0) should fix this issue :)
Please try it and check if it works for you!

**Comment by rafaeldamasceno** [comment]
Hello, everything is working fine now. Thank you for the support!
