### ISSUE TITLE
Windows Defender Detection

### ISSUE THREAD

**Issue by JoshTheBlack** [Arno500/plex-richpresence#20]
After installing and logging in, I get a notification about a virus being detected.
![image](https://github.com/Arno500/plex-richpresence/assets/15058509/e1faba70-89c4-485d-b3cd-82882dd0497d)

**Comment by Arno500** [comment]
Hello Josh
I know, Microsoft Defender LOVES to consider it as a virus.... I will report it once again to Microsoft so they remove it from their definition
