### ISSUE TITLE
"Access is denied." error with a home user account

### ISSUE THREAD

**Issue by heyitsbench** [Arno500/plex-richpresence#5]
> 2022/01/16 13:23:56 Detected language: en
2022/01/16 13:23:56 Refreshing servers
2022/01/16 13:23:58 Plex: Trying to connect to IP
2022/01/16 13:23:58 Plex: IP was successfully contacted
2022/01/16 13:23:58 Sucessfully connected to https://IP WebSocket
2022/01/16 13:24:02 A seeking or a media change was detected, adjusting
2022/01/16 13:24:02 Access is denied.

Could be related to the fact that my account is under a home with a few other users, and the app doesn't know which user I am from the `Select User` page. If that is the case, having this functionality enabled would be quite lovely.

**Comment by Arno500** [comment]
Hello @benjymansy123 

I don't know, but did you connect to the account you use to watch your media?
The Home setup here may be the issue indeed.

Adding to my backlog, when I can work on it again.
(The thing is, I never worked with Home setups because I don't have one, so I'll try as I can!)
