### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by zeroquinc** [Arno500/plex-richpresence#7]
Hi, running latest version of both plex-richpresence, Plex Server and Plex client.

Can't open the app, it crashes on startup.

Log file:

2022/02/19 20:43:23 Detected language: en
2022/02/19 20:43:23 Refreshing servers
2022/02/19 20:43:23 plexserver: Trying to connect to 192-168-0-33.f62364bfda8c4d56b037578ca86c7ac1.plex.direct:32400
2022/02/19 20:43:23 plexserver: 192-168-0-33.f62364bfda8c4d56b037578ca86c7ac1.plex.direct:32400 was successfully contacted
2022/02/19 20:43:23 Sucessfully connected to https://192-168-0-33.f62364bfda8c4d56b037578ca86c7ac1.plex.direct:32400 WebSocket
2022/02/19 20:43:28 json: cannot unmarshal array into Go struct field MetadataV1.MediaContainer.Metadata.rating of type float64

In a closed issue I saw that another user was experiencing the same problem and got fixed by updating to version 1.2.0. I tried that one and same error.

Any clue? Thanks in advance & thanks for this software!

**Comment by Arno500** [comment]
Thanks for the report @zeroquinc ,
I did not test the rating of the media and it seems it crashes on every rated media. (Plex recently changed the format of their numbers to string)
I'm fixing that ASAP ;)

**Comment by Arno500** [comment]
You may check https://github.com/Arno500/plex-richpresence/releases/tag/1.3.1
It should fix your issue ;)

**Comment by zeroquinc** [comment]
> You may check https://github.com/Arno500/plex-richpresence/releases/tag/1.3.1 It should fix your issue ;)

Thanks so much, it did fix it! 
Honestly I didn't even know I rated media on Plex myself. And double-checking it, I'm pretty sure I never did. So not sure what this means.
Thanks for your quick reply and have a nice weekend!

**Comment by AlexaRawr** [comment]
This issue was indeed fixed in 1.3.1, but occurs again in the latest release (1.5.0). Exactly the same error message. 
2022/04/27 23:31:20 json: cannot unmarshal array into Go struct field MetadataV1.MediaContainer.Metadata.rating of type float64

**Comment by Arno500** [comment]
@Pascaloli, can you try this one, please? https://github.com/Arno500/plex-richpresence/releases/tag/1.5.1
Note that if you restart the app, the autoupdater should trigger and replace the app automatically (but the filename stays the same with the old version don't worry, you should be able to see the new version by right-clicking the icon in the taskbar)

**Comment by AlexaRawr** [comment]
@Arno500 
This did not fix the issue. Heres my log

2022/04/29 01:38:04 Detected language: de
2022/04/29 01:38:05 Checking for updates...
2022/04/29 01:38:05 [AutoUpdater] Local Version 1.5.1 - Remote Version: 1.5.1
2022/04/29 01:38:05 Refreshing servers
2022/04/29 01:38:07 REDACTED: Trying to connect to REDACTED
2022/04/29 01:38:08 REDACTED: Trying to connect to REDACTED
2022/04/29 01:38:08 REDACTED was successfully contacted
2022/04/29 01:38:08 Sucessfully connected to REDACTED WebSocket
2022/04/29 01:38:08 json: cannot unmarshal string into Go struct field Rating.MediaContainer.Metadata.Rating.value of type float64

Maybe add an option to toggle a more detailed logging level, so its easier for you to track down the issue. Alternatively I can give you access to my library and tell you for which show the error occurs for me. If youre interested in that, DM me on Discord Alexа#1337
