### ISSUE TITLE
Suggestion - Add title of episode

### ISSUE THREAD

**Issue by zeroquinc** [Arno500/plex-richpresence#8]
Hi,

Currently, it only shows the Season and episode number like this.

![image](https://user-images.githubusercontent.com/39315068/154842925-6a56fedd-7c0b-4d7a-86d8-6642b9ba7e02.png)

Would be nice so that it also shows the episode name, like this: 

![image](https://user-images.githubusercontent.com/39315068/154842964-93406c2e-54ac-41f5-b626-0bc71dc3a97e.png)

Maybe also capitalize the E from episode.
It's only a minor suggestion but it would be really nice, I prefer your software above the other rich presence one.

Thanks in advance and have a nice day!

**Comment by The13thTimelord** [comment]
+1 on this :)

**Comment by Arno500** [comment]
Yeah, I think the output is cleaner on the second picture, I'll change that ;)
I'll probably do exactly as the screenshot, without the "⏏️" icon
(it's an easy fix)

**Comment by Arno500** [comment]
Available in https://github.com/Arno500/plex-richpresence/releases/tag/1.3.2 :)

**Comment by zeroquinc** [comment]
> Available in https://github.com/Arno500/plex-richpresence/releases/tag/1.3.2 :)

Looks perfect now! Thank you!
